version: "3.8"

services:
  mysql-auth-service:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: auth_db
    ports:
      - "3307:3306"

  mysql-course-service:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: course_db
    ports:
      - "3308:3306"

  mysql-grade-service:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: grade_db
    ports:
      - "3309:3306"

  mysql-enrollment-service:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: enrollment_db
    ports:
      - "3310:3306"

  auth-service:
    build:
      context: ./auth-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-auth-service:3306/auth_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - mysql-auth-service
    ports:
      - "8081:8080"

  course-service:
    build:
      context: ./course-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-course-service:3306/course_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - mysql-course-service
    ports:
      - "8082:8080"

  grade-service:
    build:
      context: ./grade-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-grade-service:3306/grade_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - mysql-grade-service
    ports:
      - "8083:8080"

  enrollment-service:
    build:
      context: ./enrollment-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-enrollment-service:3306/enrollment_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - mysql-enrollment-service
    ports:
      - "8084:8080"

  frontend:
    build:
      context: ./frontend
    ports:
      - "8000:80"
